name: Docker Build

on: 

  push:
    branches: [ develop, release/*, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, mundo!

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      if: startsWith(github.ref, 'ref/heads/release') == true
      with:
        image: frankdev/website
        tags: beta-${{ github.run_id }}, beta-latest
        registry: barrentix.azurecr.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      if: startsWith(github.ref, 'ref/heads/release')
      env:
        webhook_url: ${{ secrets.STAGING_PORTAINER_WEBHOOK }}?IMAGE_TAG=beta-${{ github.run_id }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      if: ${{ github.ref == 'ref/heads/main' }}
      with:
        image: frankdev/website
        tags: ${{ github.run_id }}, latest
        registry: barrentix.azurecr.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      if: ${{ github.ref == 'ref/heads/main' }}
      env:
        webhook_url: ${{ secrets.PRODUCTION_PORTAINER_WEBHOOK }}?IMAGE_TAG=${{ github.run_id }}