name: Docker Build

on: 

  pull_request:
    branches: [ develop, features/*, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, mundo!